<main>
    <h1 style = "color: brown">Liste des utilisateurs</h1>
    <a href="index.php?route=create_user">Créer un nouvel utilisateur</a>
    <table border="1" cellpadding="8" cellspacing ="9">
    <thead>
        <tr>
            <th>Email</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user): ?>
            <tr>
                <td><?= htmlspecialchars($user->getEmail()) ?></td>
                <td><?= htmlspecialchars($user->getFirstName()) ?></td>
                <td><?= htmlspecialchars($user->getLastName()) ?></td>
                <td>
                    <a href="index.php?route=show_user&id=<?= $user->getId() ?>">Voir</a> |
                    <a href="index.php?route=update_user&id=<?= $user->getId() ?>">Modifier</a> |
                    <a href="index.php?route=delete_user&id=<?= $user->getId() ?>" onclick="return confirm('Supprimer cet utilisateur ?')">Supprimer</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</main>
