<<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MVC J2</title>
</head>
<body>
    <nav>
        <a href="index.php">Liste</a> 
        <a href="index.php?route=show_user">Voir</a> 
        <a href="index.php?route=create_user">Créer</a> 
        <a href="index.php?route=check_create_user">Check Création</a> 
        <a href="index.php?route=update_user">Modifier</a> 
        <a href="index.php?route=check_update_user">Check Modification</a> 
        <a href="index.php?route=delete_user">Supprimer</a>
    </nav>
    <?php
    require $route;
    ?>
</body>
</html>